os: linux
language: ruby
install:
- bundle install
before_script:
- sudo apt-get install ditaa
- chmod +x build.sh
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.3.1
notifications:
  email:
    recipients:
    - mertcan.gokgoz@gmail.com
    - admin@mertcangokgoz.com
    on_success: never
    on_failure: always
env:
  global:
    secure: xxIYA11M+tc3dzdhozzvjABhPub9XC6s3TbuF1sBe2REQbtE0M3hiXXVYZk2vhc5Zpdxr1WORaTE2bpduBeuZDb4dkhk3RYH98KjKkm4CWDAFXrtjWurOwKytM56ALtnmJaClk4r8Dxc8J+z2S3iEY6MFgwxQfSGhDl3iIirWsSMV37a3o+GeTJYbjITEniOLHRr6zHRB53lclogzG5eMPbS+BVctoBCoEYl0J1Ob3hZYtggWHG03kZ7Hm6qMQHfo+fXmLVO4Qf9h3EsMwFrkBpLyqQbcS7Jtd17zJQCiy9JliBWzW1PynF7t9PRbrJYc4fot7dRNVMgydVkGfx6HxEHLRZuEGVHauFmSp+fest1hrIDWbrmaZa2WCPpUIFaMvbIy6T8friGP8PQIXp/ITOuaF3gVzwIPqP06Cx7bRkA6clQiHf+ESzEIjC3J1uC7eghkExuXLI2bFeipHuqUR1c/6QJs3rxPpcho9suCzLBggLpH8ofMA7XVposoedFmw1CbcqgGzWnu7qZgPrebV+jh+jwJtSBtXFAaSsrc7TbjoFJVojAH3wYIiKYz/VI+c6Xo6KgHhuCfTt6lDBeNrptAjKkviznbmEbenh+KSLr4l7nVPa1XkTLQI+/XNlEBavNlbvuFQ9j8JqdpnPKxSoL610PNP7xuw5KeFl34qE=
