sudo: false
language: ruby
install:
  - bundle install
before_script: chmod +x build.sh
script: "./build.sh"
branches:
  only:
  - jekyll

rvm:
- 2.3.1

notifications:
  email:
    recipients:
    - mertcan.gokgoz@gmail.com
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    secure: VirRvcQ2VXPbqbwoGobuHlj5XQfckh21Ca4hr6mne/ENZE2o1aBu1hVKTlvM4/YFVarX+a1lZcuQbE0AC1YROoF9sBI6DWROo7t2RcanM71pOjH4WNOTK6tvFPSP2CiU9WYsKJyt+ssgvXNKxuSrba4efHYLev2Qtr25FEbCnAu78WwkGscvH+wAS5rjHvRZqAvHJb/qN9569e821mPazO57WTNs+6sT4KNhzMkkyIHXUCy3RNJ86qsqsJVRBuVZ4DXV790S7B2a7plZn23IRrctyQxHcVrDONlBQYeZDrZ5B7gSbakC82y0VRhhF86POrngBFq/9t3SqgJcRF5oqQcXzDatXIyQWUg/yXJwEsmRI86QUOBNTnwxAAumh10Rj9ceHTN9UvAJhIoDkOR70ZBostEELeU1JDyCaQyL8xQvT0ExqxeKtVwK8eDxu1kHvXL8kBLxpDY8bk1YIZOTW09eBTk0KcK1rAlwXznvWOoxiUY2IPFFBrz1qZ3/MEEr2J2iOkp2oYtHxa7+hEFf6bvs8IBNp9zy89ZWV59Zsh0WqzpABXHWdxmiCAcxm9vEr1Wgi/w655BDG2MCWU4ogTOJfVn3+Iej8r0z76m9zz/G9SXEGVHZpauYXWzRuqLArQujB5StnMyThU9UXr6QmO8CX1BPtOBMIQNn5srpEp4=
