# General Jekyll Config
permalink: /:title/
paginate_path: /page/:num/
highlighter: rouge
lsi: false
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-paginate-category
  - nokogiri

#Jekyll Gist
gist:
  noscript: false

#Main Settings
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, .travis.yml, .ruby-version, .bundle, build.sh]
timezone: 'Europe/Istanbul'
encoding: 'utf-8'

#Category Pagination
category_dir: "category"
category_layout: "index.html"

#Markdown Settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

# Setup
title:            Mertcan GÖKGÖZ - Özgür Yazılım, Sunucu Yönetimi ve Hizmetleri
tagline:          Blog
description:      "Özgür yazılım üzerine GNU/Linux sistemler için sunucu yönetimi, kurulum, yapılandırma, ipuçları hakkında türkçe site"
url:              https://mertcangokgoz.com

author:
  name:           'Mertcan GÖKGÖZ'
  url:            'https://mertcangokgoz.com'
  email:          'admin@mertcangokgoz.com'
  twitter:	      'http://twitter.com/mertcangokgoz'
paginate:         22

# Custom vars
version:          3.0.0

twitter:
  username: mertcangokgoz

github:
  repo:           https://github.com/MertcanGokgoz
